// <auto-generated />
using System;
using Infra.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200727031955_seedInitialData")]
    partial class seedInitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ContactType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("Domain.Entities.Location.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Complement")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("District")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<float>("Latitude")
                        .HasColumnType("float");

                    b.Property<float>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Number")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("StateId")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ZipCode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.HasIndex("StateId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Domain.Entities.Location.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("IBGECode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("IdState")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("City");
                });

            modelBuilder.Entity("Domain.Entities.Location.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bacen")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Initials")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name_PT")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bacen = "1058",
                            Initials = "BR",
                            Name = "Brazil",
                            Name_PT = "Brasil"
                        },
                        new
                        {
                            Id = 2,
                            Bacen = "132",
                            Initials = "AF",
                            Name = "Afghanistan",
                            Name_PT = "Afeganistão"
                        },
                        new
                        {
                            Id = 3,
                            Bacen = "175",
                            Initials = "AL",
                            Name = "Albania",
                            Name_PT = "Albânia, Republica da"
                        },
                        new
                        {
                            Id = 4,
                            Bacen = "590",
                            Initials = "DZ",
                            Name = "Algeria",
                            Name_PT = "Argélia"
                        },
                        new
                        {
                            Id = 5,
                            Bacen = "6912",
                            Initials = "AS",
                            Name = "American Samoa",
                            Name_PT = "Samoa Americana"
                        },
                        new
                        {
                            Id = 6,
                            Bacen = "370",
                            Initials = "AD",
                            Name = "Andorra",
                            Name_PT = "Andorra"
                        },
                        new
                        {
                            Id = 7,
                            Bacen = "400",
                            Initials = "AO",
                            Name = "Angola",
                            Name_PT = "Angola"
                        },
                        new
                        {
                            Id = 8,
                            Bacen = "418",
                            Initials = "AI",
                            Name = "Anguilla",
                            Name_PT = "Anguilla"
                        },
                        new
                        {
                            Id = 9,
                            Bacen = "3596",
                            Initials = "AQ",
                            Name = "Antarctica",
                            Name_PT = "Antártida"
                        },
                        new
                        {
                            Id = 10,
                            Bacen = "434",
                            Initials = "AG",
                            Name = "Antigua and Barbuda",
                            Name_PT = "Antigua e Barbuda"
                        },
                        new
                        {
                            Id = 11,
                            Bacen = "639",
                            Initials = "AR",
                            Name = "Argentina",
                            Name_PT = "Argentina"
                        },
                        new
                        {
                            Id = 12,
                            Bacen = "647",
                            Initials = "AM",
                            Name = "Armenia",
                            Name_PT = "Armênia, Republica da"
                        },
                        new
                        {
                            Id = 13,
                            Bacen = "655",
                            Initials = "AW",
                            Name = "Aruba",
                            Name_PT = "Aruba"
                        },
                        new
                        {
                            Id = 14,
                            Bacen = "698",
                            Initials = "AU",
                            Name = "Australia",
                            Name_PT = "Austrália"
                        },
                        new
                        {
                            Id = 15,
                            Bacen = "728",
                            Initials = "AT",
                            Name = "Austria",
                            Name_PT = "Áustria"
                        },
                        new
                        {
                            Id = 16,
                            Bacen = "736",
                            Initials = "AZ",
                            Name = "Azerbaijan",
                            Name_PT = "Azerbaijão, Republica do"
                        },
                        new
                        {
                            Id = 17,
                            Bacen = "779",
                            Initials = "BS",
                            Name = "Bahamas",
                            Name_PT = "Bahamas, Ilhas"
                        },
                        new
                        {
                            Id = 18,
                            Bacen = "809",
                            Initials = "BH",
                            Name = "Bahrain",
                            Name_PT = "Bahrein, Ilhas"
                        },
                        new
                        {
                            Id = 19,
                            Bacen = "817",
                            Initials = "BD",
                            Name = "Bangladesh",
                            Name_PT = "Bangladesh"
                        },
                        new
                        {
                            Id = 20,
                            Bacen = "833",
                            Initials = "BB",
                            Name = "Barbados",
                            Name_PT = "Barbados"
                        },
                        new
                        {
                            Id = 21,
                            Bacen = "850",
                            Initials = "BY",
                            Name = "Belarus",
                            Name_PT = "Belarus, Republica da"
                        },
                        new
                        {
                            Id = 22,
                            Bacen = "876",
                            Initials = "BE",
                            Name = "Belgium",
                            Name_PT = "Bélgica"
                        },
                        new
                        {
                            Id = 23,
                            Bacen = "884",
                            Initials = "BZ",
                            Name = "Belize",
                            Name_PT = "Belize"
                        },
                        new
                        {
                            Id = 24,
                            Bacen = "2291",
                            Initials = "BJ",
                            Name = "Benin",
                            Name_PT = "Benin"
                        },
                        new
                        {
                            Id = 25,
                            Bacen = "906",
                            Initials = "BM",
                            Name = "Bermuda",
                            Name_PT = "Bermudas"
                        },
                        new
                        {
                            Id = 26,
                            Bacen = "1198",
                            Initials = "BT",
                            Name = "Bhutan",
                            Name_PT = "Butão"
                        },
                        new
                        {
                            Id = 27,
                            Bacen = "973",
                            Initials = "BO",
                            Name = "Bolivia",
                            Name_PT = "Bolívia"
                        },
                        new
                        {
                            Id = 28,
                            Bacen = "981",
                            Initials = "BA",
                            Name = "Bosnia and Herzegowina",
                            Name_PT = "Bósnia-herzegovina (Republica da)"
                        },
                        new
                        {
                            Id = 29,
                            Bacen = "1015",
                            Initials = "BW",
                            Name = "Botswana",
                            Name_PT = "Botsuana"
                        },
                        new
                        {
                            Id = 30,
                            Bacen = "1023",
                            Initials = "BV",
                            Name = "Bouvet Island",
                            Name_PT = "Bouvet, Ilha"
                        },
                        new
                        {
                            Id = 31,
                            Bacen = "7820",
                            Initials = "IO",
                            Name = "British Indian Ocean Territory",
                            Name_PT = "Território Britânico do Oceano Indico"
                        },
                        new
                        {
                            Id = 32,
                            Bacen = "1082",
                            Initials = "BN",
                            Name = "Brunei Darussalam",
                            Name_PT = "Brunei"
                        },
                        new
                        {
                            Id = 33,
                            Bacen = "1112",
                            Initials = "BG",
                            Name = "Bulgaria",
                            Name_PT = "Bulgária, Republica da"
                        },
                        new
                        {
                            Id = 34,
                            Bacen = "310",
                            Initials = "BF",
                            Name = "Burkina Faso",
                            Name_PT = "Burkina Faso"
                        },
                        new
                        {
                            Id = 35,
                            Bacen = "1155",
                            Initials = "BI",
                            Name = "Burundi",
                            Name_PT = "Burundi"
                        },
                        new
                        {
                            Id = 36,
                            Bacen = "1414",
                            Initials = "KH",
                            Name = "Cambodia",
                            Name_PT = "Camboja"
                        },
                        new
                        {
                            Id = 37,
                            Bacen = "1457",
                            Initials = "CM",
                            Name = "Cameroon",
                            Name_PT = "Camarões"
                        },
                        new
                        {
                            Id = 38,
                            Bacen = "1490",
                            Initials = "CA",
                            Name = "Canada",
                            Name_PT = "Canada"
                        },
                        new
                        {
                            Id = 39,
                            Bacen = "1279",
                            Initials = "CV",
                            Name = "Cape Verde",
                            Name_PT = "Cabo Verde, Republica de"
                        },
                        new
                        {
                            Id = 40,
                            Bacen = "1376",
                            Initials = "KY",
                            Name = "Cayman Islands",
                            Name_PT = "Cayman, Ilhas"
                        },
                        new
                        {
                            Id = 41,
                            Bacen = "6408",
                            Initials = "CF",
                            Name = "Central African Republic",
                            Name_PT = "Republica Centro-Africana"
                        },
                        new
                        {
                            Id = 42,
                            Bacen = "7889",
                            Initials = "TD",
                            Name = "Chad",
                            Name_PT = "Chade"
                        },
                        new
                        {
                            Id = 43,
                            Bacen = "1589",
                            Initials = "CL",
                            Name = "Chile",
                            Name_PT = "Chile"
                        },
                        new
                        {
                            Id = 44,
                            Bacen = "1600",
                            Initials = "CN",
                            Name = "China",
                            Name_PT = "China, Republica Popular"
                        },
                        new
                        {
                            Id = 45,
                            Bacen = "5118",
                            Initials = "CX",
                            Name = "Christmas Island",
                            Name_PT = "Christmas, Ilha (Navidad)"
                        },
                        new
                        {
                            Id = 46,
                            Bacen = "1651",
                            Initials = "CC",
                            Name = "Cocos (Keeling) Islands",
                            Name_PT = "Cocos (Keeling), Ilhas"
                        },
                        new
                        {
                            Id = 47,
                            Bacen = "1694",
                            Initials = "CO",
                            Name = "Colombia",
                            Name_PT = "Colômbia"
                        },
                        new
                        {
                            Id = 48,
                            Bacen = "1732",
                            Initials = "KM",
                            Name = "Comoros",
                            Name_PT = "Comores, Ilhas"
                        },
                        new
                        {
                            Id = 49,
                            Bacen = "1775",
                            Initials = "CG",
                            Name = "Congo",
                            Name_PT = "Congo"
                        },
                        new
                        {
                            Id = 50,
                            Bacen = "8885",
                            Initials = "CD",
                            Name = "Congo, the Democratic Republic of the",
                            Name_PT = "Congo, Republica Democrática do"
                        },
                        new
                        {
                            Id = 51,
                            Bacen = "1830",
                            Initials = "CK",
                            Name = "Cook Islands",
                            Name_PT = "Cook, Ilhas"
                        },
                        new
                        {
                            Id = 52,
                            Bacen = "1961",
                            Initials = "CR",
                            Name = "Costa Rica",
                            Name_PT = "Costa Rica"
                        },
                        new
                        {
                            Id = 53,
                            Bacen = "1937",
                            Initials = "CI",
                            Name = "Cote d`Ivoire",
                            Name_PT = "Costa do Marfim"
                        },
                        new
                        {
                            Id = 54,
                            Bacen = "1953",
                            Initials = "HR",
                            Name = "Croatia (Hrvatska)",
                            Name_PT = "Croácia (Republica da)"
                        },
                        new
                        {
                            Id = 55,
                            Bacen = "1996",
                            Initials = "CU",
                            Name = "Cuba",
                            Name_PT = "Cuba"
                        },
                        new
                        {
                            Id = 56,
                            Bacen = "1635",
                            Initials = "CY",
                            Name = "Cyprus",
                            Name_PT = "Chipre"
                        },
                        new
                        {
                            Id = 57,
                            Bacen = "7919",
                            Initials = "CZ",
                            Name = "Czech Republic",
                            Name_PT = "Tcheca, Republica"
                        },
                        new
                        {
                            Id = 58,
                            Bacen = "2321",
                            Initials = "DK",
                            Name = "Denmark",
                            Name_PT = "Dinamarca"
                        },
                        new
                        {
                            Id = 59,
                            Bacen = "7838",
                            Initials = "DJ",
                            Name = "Djibouti",
                            Name_PT = "Djibuti"
                        },
                        new
                        {
                            Id = 60,
                            Bacen = "2356",
                            Initials = "DM",
                            Name = "Dominica",
                            Name_PT = "Dominica, Ilha"
                        },
                        new
                        {
                            Id = 61,
                            Bacen = "6475",
                            Initials = "DO",
                            Name = "Dominican Republic",
                            Name_PT = "Republica Dominicana"
                        },
                        new
                        {
                            Id = 62,
                            Bacen = "7951",
                            Initials = "TL",
                            Name = "East Timor",
                            Name_PT = "Timor Leste"
                        },
                        new
                        {
                            Id = 63,
                            Bacen = "2399",
                            Initials = "EC",
                            Name = "Ecuador",
                            Name_PT = "Equador"
                        },
                        new
                        {
                            Id = 64,
                            Bacen = "2402",
                            Initials = "EG",
                            Name = "Egypt",
                            Name_PT = "Egito"
                        },
                        new
                        {
                            Id = 65,
                            Bacen = "6874",
                            Initials = "SV",
                            Name = "El Salvador",
                            Name_PT = "El Salvador"
                        },
                        new
                        {
                            Id = 66,
                            Bacen = "3310",
                            Initials = "GQ",
                            Name = "Equatorial Guinea",
                            Name_PT = "Guine-Equatorial"
                        },
                        new
                        {
                            Id = 67,
                            Bacen = "2437",
                            Initials = "ER",
                            Name = "Eritrea",
                            Name_PT = "Eritreia"
                        },
                        new
                        {
                            Id = 68,
                            Bacen = "2518",
                            Initials = "EE",
                            Name = "Estonia",
                            Name_PT = "Estônia, Republica da"
                        },
                        new
                        {
                            Id = 69,
                            Bacen = "2534",
                            Initials = "ET",
                            Name = "Ethiopia",
                            Name_PT = "Etiópia"
                        },
                        new
                        {
                            Id = 70,
                            Bacen = "2550",
                            Initials = "FK",
                            Name = "Falkland Islands (Malvinas)",
                            Name_PT = "Falkland (Ilhas Malvinas)"
                        },
                        new
                        {
                            Id = 71,
                            Bacen = "2593",
                            Initials = "FO",
                            Name = "Faroe Islands",
                            Name_PT = "Feroe, Ilhas"
                        },
                        new
                        {
                            Id = 72,
                            Bacen = "8702",
                            Initials = "FJ",
                            Name = "Fiji",
                            Name_PT = "Fiji"
                        },
                        new
                        {
                            Id = 73,
                            Bacen = "2712",
                            Initials = "FI",
                            Name = "Finland",
                            Name_PT = "Finlândia"
                        },
                        new
                        {
                            Id = 74,
                            Bacen = "2755",
                            Initials = "FR",
                            Name = "France",
                            Name_PT = "Franca"
                        },
                        new
                        {
                            Id = 76,
                            Bacen = "3255",
                            Initials = "GF",
                            Name = "French Guiana",
                            Name_PT = "Guiana francesa"
                        },
                        new
                        {
                            Id = 77,
                            Bacen = "5991",
                            Initials = "PF",
                            Name = "French Polynesia",
                            Name_PT = "Polinésia Francesa"
                        },
                        new
                        {
                            Id = 78,
                            Bacen = "3607",
                            Initials = "TF",
                            Name = "French Southern Territories",
                            Name_PT = "Terras Austrais e Antárticas Francesas"
                        },
                        new
                        {
                            Id = 79,
                            Bacen = "2810",
                            Initials = "GA",
                            Name = "Gabon",
                            Name_PT = "Gabão"
                        },
                        new
                        {
                            Id = 80,
                            Bacen = "2852",
                            Initials = "GM",
                            Name = "Gambia",
                            Name_PT = "Gambia"
                        },
                        new
                        {
                            Id = 81,
                            Bacen = "2917",
                            Initials = "GE",
                            Name = "Georgia",
                            Name_PT = "Georgia, Republica da"
                        },
                        new
                        {
                            Id = 82,
                            Bacen = "230",
                            Initials = "DE",
                            Name = "Germany",
                            Name_PT = "Alemanha"
                        },
                        new
                        {
                            Id = 83,
                            Bacen = "2895",
                            Initials = "GH",
                            Name = "Ghana",
                            Name_PT = "Gana"
                        },
                        new
                        {
                            Id = 84,
                            Bacen = "2933",
                            Initials = "GI",
                            Name = "Gibraltar",
                            Name_PT = "Gibraltar"
                        },
                        new
                        {
                            Id = 85,
                            Bacen = "3018",
                            Initials = "GR",
                            Name = "Greece",
                            Name_PT = "Grécia"
                        },
                        new
                        {
                            Id = 86,
                            Bacen = "3050",
                            Initials = "GL",
                            Name = "Greenland",
                            Name_PT = "Groenlândia"
                        },
                        new
                        {
                            Id = 87,
                            Bacen = "2976",
                            Initials = "GD",
                            Name = "Grenada",
                            Name_PT = "Granada"
                        },
                        new
                        {
                            Id = 88,
                            Bacen = "3093",
                            Initials = "GP",
                            Name = "Guadeloupe",
                            Name_PT = "Guadalupe"
                        },
                        new
                        {
                            Id = 89,
                            Bacen = "3131",
                            Initials = "GU",
                            Name = "Guam",
                            Name_PT = "Guam"
                        },
                        new
                        {
                            Id = 90,
                            Bacen = "3174",
                            Initials = "GT",
                            Name = "Guatemala",
                            Name_PT = "Guatemala"
                        },
                        new
                        {
                            Id = 91,
                            Bacen = "3298",
                            Initials = "GN",
                            Name = "Guinea",
                            Name_PT = "Guine"
                        },
                        new
                        {
                            Id = 92,
                            Bacen = "3344",
                            Initials = "GW",
                            Name = "Guinea-Bissau",
                            Name_PT = "Guine-Bissau"
                        },
                        new
                        {
                            Id = 93,
                            Bacen = "3379",
                            Initials = "GY",
                            Name = "Guyana",
                            Name_PT = "Guiana"
                        },
                        new
                        {
                            Id = 94,
                            Bacen = "3417",
                            Initials = "HT",
                            Name = "Haiti",
                            Name_PT = "Haiti"
                        },
                        new
                        {
                            Id = 95,
                            Bacen = "3603",
                            Initials = "HM",
                            Name = "Heard and Mc Donald Islands",
                            Name_PT = "Ilha Heard e Ilhas McDonald"
                        },
                        new
                        {
                            Id = 96,
                            Bacen = "8486",
                            Initials = "VA",
                            Name = "Holy See (Vatican City State)",
                            Name_PT = "Vaticano, Estado da Cidade do"
                        },
                        new
                        {
                            Id = 97,
                            Bacen = "3450",
                            Initials = "HN",
                            Name = "Honduras",
                            Name_PT = "Honduras"
                        },
                        new
                        {
                            Id = 98,
                            Bacen = "3514",
                            Initials = "HK",
                            Name = "Hong Kong",
                            Name_PT = "Hong Kong"
                        },
                        new
                        {
                            Id = 99,
                            Bacen = "3557",
                            Initials = "HU",
                            Name = "Hungary",
                            Name_PT = "Hungria, Republica da"
                        },
                        new
                        {
                            Id = 100,
                            Bacen = "3794",
                            Initials = "IS",
                            Name = "Iceland",
                            Name_PT = "Islândia"
                        },
                        new
                        {
                            Id = 101,
                            Bacen = "3611",
                            Initials = "IN",
                            Name = "India",
                            Name_PT = "Índia"
                        },
                        new
                        {
                            Id = 102,
                            Bacen = "3654",
                            Initials = "ID",
                            Name = "Indonesia",
                            Name_PT = "Indonésia"
                        },
                        new
                        {
                            Id = 103,
                            Bacen = "3727",
                            Initials = "IR",
                            Name = "Iran (Islamic Republic of)",
                            Name_PT = "Ira, Republica Islâmica do"
                        },
                        new
                        {
                            Id = 104,
                            Bacen = "3697",
                            Initials = "IQ",
                            Name = "Iraq",
                            Name_PT = "Iraque"
                        },
                        new
                        {
                            Id = 105,
                            Bacen = "3751",
                            Initials = "IE",
                            Name = "Ireland",
                            Name_PT = "Irlanda"
                        },
                        new
                        {
                            Id = 106,
                            Bacen = "3832",
                            Initials = "IL",
                            Name = "Israel",
                            Name_PT = "Israel"
                        },
                        new
                        {
                            Id = 107,
                            Bacen = "3867",
                            Initials = "IT",
                            Name = "Italy",
                            Name_PT = "Itália"
                        },
                        new
                        {
                            Id = 108,
                            Bacen = "3913",
                            Initials = "JM",
                            Name = "Jamaica",
                            Name_PT = "Jamaica"
                        },
                        new
                        {
                            Id = 109,
                            Bacen = "3999",
                            Initials = "JP",
                            Name = "Japan",
                            Name_PT = "Japão"
                        },
                        new
                        {
                            Id = 110,
                            Bacen = "4030",
                            Initials = "JO",
                            Name = "Jordan",
                            Name_PT = "Jordânia"
                        },
                        new
                        {
                            Id = 111,
                            Bacen = "1538",
                            Initials = "KZ",
                            Name = "Kazakhstan",
                            Name_PT = "Cazaquistão, Republica do"
                        },
                        new
                        {
                            Id = 112,
                            Bacen = "6238",
                            Initials = "KE",
                            Name = "Kenya",
                            Name_PT = "Quênia"
                        },
                        new
                        {
                            Id = 113,
                            Bacen = "4111",
                            Initials = "KI",
                            Name = "Kiribati",
                            Name_PT = "Kiribati"
                        },
                        new
                        {
                            Id = 114,
                            Bacen = "1872",
                            Initials = "KP",
                            Name = "Korea, Democratic People`s Republic of",
                            Name_PT = "Coreia, Republica Popular Democrática da"
                        },
                        new
                        {
                            Id = 115,
                            Bacen = "1902",
                            Initials = "KR",
                            Name = "Korea, Republic of",
                            Name_PT = "Coreia, Republica da"
                        },
                        new
                        {
                            Id = 116,
                            Bacen = "1988",
                            Initials = "KW",
                            Name = "Kuwait",
                            Name_PT = "Kuwait"
                        },
                        new
                        {
                            Id = 117,
                            Bacen = "6254",
                            Initials = "KG",
                            Name = "Kyrgyzstan",
                            Name_PT = "Quirguiz, Republica"
                        },
                        new
                        {
                            Id = 118,
                            Bacen = "4200",
                            Initials = "LA",
                            Name = "Lao People`s Democratic Republic",
                            Name_PT = "Laos, Republica Popular Democrática do"
                        },
                        new
                        {
                            Id = 119,
                            Bacen = "4278",
                            Initials = "LV",
                            Name = "Latvia",
                            Name_PT = "Letônia, Republica da"
                        },
                        new
                        {
                            Id = 120,
                            Bacen = "4316",
                            Initials = "LB",
                            Name = "Lebanon",
                            Name_PT = "Líbano"
                        },
                        new
                        {
                            Id = 121,
                            Bacen = "4260",
                            Initials = "LS",
                            Name = "Lesotho",
                            Name_PT = "Lesoto"
                        },
                        new
                        {
                            Id = 122,
                            Bacen = "4340",
                            Initials = "LR",
                            Name = "Liberia",
                            Name_PT = "Libéria"
                        },
                        new
                        {
                            Id = 123,
                            Bacen = "4383",
                            Initials = "LY",
                            Name = "Libyan Arab Jamahiriya",
                            Name_PT = "Líbia"
                        },
                        new
                        {
                            Id = 124,
                            Bacen = "4405",
                            Initials = "LI",
                            Name = "Liechtenstein",
                            Name_PT = "Liechtenstein"
                        },
                        new
                        {
                            Id = 125,
                            Bacen = "4421",
                            Initials = "LT",
                            Name = "Lithuania",
                            Name_PT = "Lituânia, Republica da"
                        },
                        new
                        {
                            Id = 126,
                            Bacen = "4456",
                            Initials = "LU",
                            Name = "Luxembourg",
                            Name_PT = "Luxemburgo"
                        },
                        new
                        {
                            Id = 127,
                            Bacen = "4472",
                            Initials = "MO",
                            Name = "Macau",
                            Name_PT = "Macau"
                        },
                        new
                        {
                            Id = 128,
                            Bacen = "4499",
                            Initials = "MK",
                            Name = "North Macedonia",
                            Name_PT = "Macedônia do Norte"
                        },
                        new
                        {
                            Id = 129,
                            Bacen = "4502",
                            Initials = "MG",
                            Name = "Madagascar",
                            Name_PT = "Madagascar"
                        },
                        new
                        {
                            Id = 130,
                            Bacen = "4588",
                            Initials = "MW",
                            Name = "Malawi",
                            Name_PT = "Malavi"
                        },
                        new
                        {
                            Id = 131,
                            Bacen = "4553",
                            Initials = "MY",
                            Name = "Malaysia",
                            Name_PT = "Malásia"
                        },
                        new
                        {
                            Id = 132,
                            Bacen = "4618",
                            Initials = "MV",
                            Name = "Maldives",
                            Name_PT = "Maldivas"
                        },
                        new
                        {
                            Id = 133,
                            Bacen = "4642",
                            Initials = "ML",
                            Name = "Mali",
                            Name_PT = "Mali"
                        },
                        new
                        {
                            Id = 134,
                            Bacen = "4677",
                            Initials = "MT",
                            Name = "Malta",
                            Name_PT = "Malta"
                        },
                        new
                        {
                            Id = 135,
                            Bacen = "4766",
                            Initials = "MH",
                            Name = "Marshall Islands",
                            Name_PT = "Marshall, Ilhas"
                        },
                        new
                        {
                            Id = 136,
                            Bacen = "4774",
                            Initials = "MQ",
                            Name = "Martinique",
                            Name_PT = "Martinica"
                        },
                        new
                        {
                            Id = 137,
                            Bacen = "4880",
                            Initials = "MR",
                            Name = "Mauritania",
                            Name_PT = "Mauritânia"
                        },
                        new
                        {
                            Id = 138,
                            Bacen = "4855",
                            Initials = "MU",
                            Name = "Mauritius",
                            Name_PT = "Mauricio"
                        },
                        new
                        {
                            Id = 139,
                            Bacen = "4885",
                            Initials = "YT",
                            Name = "Mayotte",
                            Name_PT = "Mayotte (Ilhas Francesas)"
                        },
                        new
                        {
                            Id = 140,
                            Bacen = "4936",
                            Initials = "MX",
                            Name = "Mexico",
                            Name_PT = "México"
                        },
                        new
                        {
                            Id = 141,
                            Bacen = "4995",
                            Initials = "FM",
                            Name = "Micronesia, Federated States of",
                            Name_PT = "Micronesia"
                        },
                        new
                        {
                            Id = 142,
                            Bacen = "4944",
                            Initials = "MD",
                            Name = "Moldova, Republic of",
                            Name_PT = "Moldávia, Republica da"
                        },
                        new
                        {
                            Id = 143,
                            Bacen = "4952",
                            Initials = "MC",
                            Name = "Monaco",
                            Name_PT = "Mônaco"
                        },
                        new
                        {
                            Id = 144,
                            Bacen = "4979",
                            Initials = "MN",
                            Name = "Mongolia",
                            Name_PT = "Mongólia"
                        },
                        new
                        {
                            Id = 145,
                            Bacen = "5010",
                            Initials = "MS",
                            Name = "Montserrat",
                            Name_PT = "Montserrat, Ilhas"
                        },
                        new
                        {
                            Id = 146,
                            Bacen = "4740",
                            Initials = "MA",
                            Name = "Morocco",
                            Name_PT = "Marrocos"
                        },
                        new
                        {
                            Id = 147,
                            Bacen = "5053",
                            Initials = "MZ",
                            Name = "Mozambique",
                            Name_PT = "Moçambique"
                        },
                        new
                        {
                            Id = 148,
                            Bacen = "930",
                            Initials = "MM",
                            Name = "Myanmar",
                            Name_PT = "Mianmar (Birmânia)"
                        },
                        new
                        {
                            Id = 149,
                            Bacen = "5070",
                            Initials = "NA",
                            Name = "Namibia",
                            Name_PT = "Namíbia"
                        },
                        new
                        {
                            Id = 150,
                            Bacen = "5088",
                            Initials = "NR",
                            Name = "Nauru",
                            Name_PT = "Nauru"
                        },
                        new
                        {
                            Id = 151,
                            Bacen = "5177",
                            Initials = "NP",
                            Name = "Nepal",
                            Name_PT = "Nepal"
                        },
                        new
                        {
                            Id = 152,
                            Bacen = "5738",
                            Initials = "NL",
                            Name = "Netherlands",
                            Name_PT = "Países Baixos (Holanda)"
                        },
                        new
                        {
                            Id = 154,
                            Bacen = "5428",
                            Initials = "NC",
                            Name = "New Caledonia",
                            Name_PT = "Nova Caledonia"
                        },
                        new
                        {
                            Id = 155,
                            Bacen = "5487",
                            Initials = "NZ",
                            Name = "New Zealand",
                            Name_PT = "Nova Zelândia"
                        },
                        new
                        {
                            Id = 156,
                            Bacen = "5215",
                            Initials = "NI",
                            Name = "Nicaragua",
                            Name_PT = "Nicarágua"
                        },
                        new
                        {
                            Id = 157,
                            Bacen = "5258",
                            Initials = "NE",
                            Name = "Niger",
                            Name_PT = "Níger"
                        },
                        new
                        {
                            Id = 158,
                            Bacen = "5282",
                            Initials = "NG",
                            Name = "Nigeria",
                            Name_PT = "Nigéria"
                        },
                        new
                        {
                            Id = 159,
                            Bacen = "5312",
                            Initials = "NU",
                            Name = "Niue",
                            Name_PT = "Niue, Ilha"
                        },
                        new
                        {
                            Id = 160,
                            Bacen = "5355",
                            Initials = "NF",
                            Name = "Norfolk Island",
                            Name_PT = "Norfolk, Ilha"
                        },
                        new
                        {
                            Id = 161,
                            Bacen = "4723",
                            Initials = "MP",
                            Name = "Northern Mariana Islands",
                            Name_PT = "Marianas do Norte"
                        },
                        new
                        {
                            Id = 162,
                            Bacen = "5380",
                            Initials = "NO",
                            Name = "Norway",
                            Name_PT = "Noruega"
                        },
                        new
                        {
                            Id = 163,
                            Bacen = "5568",
                            Initials = "OM",
                            Name = "Oman",
                            Name_PT = "Oma"
                        },
                        new
                        {
                            Id = 164,
                            Bacen = "5762",
                            Initials = "PK",
                            Name = "Pakistan",
                            Name_PT = "Paquistão"
                        },
                        new
                        {
                            Id = 165,
                            Bacen = "5754",
                            Initials = "PW",
                            Name = "Palau",
                            Name_PT = "Palau"
                        },
                        new
                        {
                            Id = 166,
                            Bacen = "5800",
                            Initials = "PA",
                            Name = "Panama",
                            Name_PT = "Panamá"
                        },
                        new
                        {
                            Id = 167,
                            Bacen = "5452",
                            Initials = "PG",
                            Name = "Papua New Guinea",
                            Name_PT = "Papua Nova Guine"
                        },
                        new
                        {
                            Id = 168,
                            Bacen = "5860",
                            Initials = "PY",
                            Name = "Paraguay",
                            Name_PT = "Paraguai"
                        },
                        new
                        {
                            Id = 169,
                            Bacen = "5894",
                            Initials = "PE",
                            Name = "Peru",
                            Name_PT = "Peru"
                        },
                        new
                        {
                            Id = 170,
                            Bacen = "2674",
                            Initials = "PH",
                            Name = "Philippines",
                            Name_PT = "Filipinas"
                        },
                        new
                        {
                            Id = 171,
                            Bacen = "5932",
                            Initials = "PN",
                            Name = "Pitcairn",
                            Name_PT = "Pitcairn, Ilha"
                        },
                        new
                        {
                            Id = 172,
                            Bacen = "6033",
                            Initials = "PL",
                            Name = "Poland",
                            Name_PT = "Polônia, Republica da"
                        },
                        new
                        {
                            Id = 173,
                            Bacen = "6076",
                            Initials = "PT",
                            Name = "Portugal",
                            Name_PT = "Portugal"
                        },
                        new
                        {
                            Id = 174,
                            Bacen = "6114",
                            Initials = "PR",
                            Name = "Puerto Rico",
                            Name_PT = "Porto Rico"
                        },
                        new
                        {
                            Id = 175,
                            Bacen = "1546",
                            Initials = "QA",
                            Name = "Qatar",
                            Name_PT = "Catar"
                        },
                        new
                        {
                            Id = 176,
                            Bacen = "6602",
                            Initials = "RE",
                            Name = "Reunion",
                            Name_PT = "Reunião, Ilha"
                        },
                        new
                        {
                            Id = 177,
                            Bacen = "6700",
                            Initials = "RO",
                            Name = "Romania",
                            Name_PT = "Romênia"
                        },
                        new
                        {
                            Id = 178,
                            Bacen = "6769",
                            Initials = "RU",
                            Name = "Russian Federation",
                            Name_PT = "Rússia, Federação da"
                        },
                        new
                        {
                            Id = 179,
                            Bacen = "6750",
                            Initials = "RW",
                            Name = "Rwanda",
                            Name_PT = "Ruanda"
                        },
                        new
                        {
                            Id = 180,
                            Bacen = "6955",
                            Initials = "KN",
                            Name = "Saint Kitts and Nevis",
                            Name_PT = "São Cristovão e Neves, Ilhas"
                        },
                        new
                        {
                            Id = 181,
                            Bacen = "7153",
                            Initials = "LC",
                            Name = "Saint LUCIA",
                            Name_PT = "Santa Lucia"
                        },
                        new
                        {
                            Id = 182,
                            Bacen = "7056",
                            Initials = "VC",
                            Name = "Saint Vincent and the Grenadines",
                            Name_PT = "São Vicente e Granadinas"
                        },
                        new
                        {
                            Id = 183,
                            Bacen = "6904",
                            Initials = "WS",
                            Name = "Samoa",
                            Name_PT = "Samoa"
                        },
                        new
                        {
                            Id = 184,
                            Bacen = "6971",
                            Initials = "SM",
                            Name = "San Marino",
                            Name_PT = "San Marino"
                        },
                        new
                        {
                            Id = 185,
                            Bacen = "7200",
                            Initials = "ST",
                            Name = "Sao Tome and Principe",
                            Name_PT = "São Tome e Príncipe, Ilhas"
                        },
                        new
                        {
                            Id = 186,
                            Bacen = "531",
                            Initials = "SA",
                            Name = "Saudi Arabia",
                            Name_PT = "Arábia Saudita"
                        },
                        new
                        {
                            Id = 187,
                            Bacen = "7285",
                            Initials = "SN",
                            Name = "Senegal",
                            Name_PT = "Senegal"
                        },
                        new
                        {
                            Id = 188,
                            Bacen = "7315",
                            Initials = "SC",
                            Name = "Seychelles",
                            Name_PT = "Seychelles"
                        },
                        new
                        {
                            Id = 189,
                            Bacen = "7358",
                            Initials = "SL",
                            Name = "Sierra Leone",
                            Name_PT = "Serra Leoa"
                        },
                        new
                        {
                            Id = 190,
                            Bacen = "7412",
                            Initials = "SG",
                            Name = "Singapore",
                            Name_PT = "Cingapura"
                        },
                        new
                        {
                            Id = 191,
                            Bacen = "2470",
                            Initials = "SK",
                            Name = "Slovakia (Slovak Republic)",
                            Name_PT = "Eslovaca, Republica"
                        },
                        new
                        {
                            Id = 192,
                            Bacen = "2461",
                            Initials = "SI",
                            Name = "Slovenia",
                            Name_PT = "Eslovênia, Republica da"
                        },
                        new
                        {
                            Id = 193,
                            Bacen = "6777",
                            Initials = "SB",
                            Name = "Solomon Islands",
                            Name_PT = "Salomão, Ilhas"
                        },
                        new
                        {
                            Id = 194,
                            Bacen = "7480",
                            Initials = "SO",
                            Name = "Somalia",
                            Name_PT = "Somalia"
                        },
                        new
                        {
                            Id = 195,
                            Bacen = "7560",
                            Initials = "ZA",
                            Name = "South Africa",
                            Name_PT = "África do Sul"
                        },
                        new
                        {
                            Id = 196,
                            Bacen = "2925",
                            Initials = "GS",
                            Name = "South Georgia and the South Sandwich Islands",
                            Name_PT = "Ilhas Geórgia do Sul e Sandwich do Sul"
                        },
                        new
                        {
                            Id = 197,
                            Bacen = "2453",
                            Initials = "ES",
                            Name = "Spain",
                            Name_PT = "Espanha"
                        },
                        new
                        {
                            Id = 198,
                            Bacen = "7501",
                            Initials = "LK",
                            Name = "Sri Lanka",
                            Name_PT = "Sri Lanka"
                        },
                        new
                        {
                            Id = 199,
                            Bacen = "7102",
                            Initials = "SH",
                            Name = "St. Helena",
                            Name_PT = "Santa Helena"
                        },
                        new
                        {
                            Id = 200,
                            Bacen = "7005",
                            Initials = "PM",
                            Name = "St. Pierre and Miquelon",
                            Name_PT = "São Pedro e Miquelon"
                        },
                        new
                        {
                            Id = 201,
                            Bacen = "7595",
                            Initials = "SD",
                            Name = "Sudan",
                            Name_PT = "Sudão"
                        },
                        new
                        {
                            Id = 202,
                            Bacen = "7706",
                            Initials = "SR",
                            Name = "Suriname",
                            Name_PT = "Suriname"
                        },
                        new
                        {
                            Id = 203,
                            Bacen = "7552",
                            Initials = "SJ",
                            Name = "Svalbard and Jan Mayen Islands",
                            Name_PT = "Svalbard e Jan Mayen"
                        },
                        new
                        {
                            Id = 204,
                            Bacen = "7544",
                            Initials = "SZ",
                            Name = "Swaziland",
                            Name_PT = "Eswatini"
                        },
                        new
                        {
                            Id = 205,
                            Bacen = "7641",
                            Initials = "SE",
                            Name = "Sweden",
                            Name_PT = "Suécia"
                        },
                        new
                        {
                            Id = 206,
                            Bacen = "7676",
                            Initials = "CH",
                            Name = "Switzerland",
                            Name_PT = "Suíça"
                        },
                        new
                        {
                            Id = 207,
                            Bacen = "7447",
                            Initials = "SY",
                            Name = "Syrian Arab Republic",
                            Name_PT = "Síria, Republica Árabe da"
                        },
                        new
                        {
                            Id = 208,
                            Bacen = "1619",
                            Initials = "TW",
                            Name = "Taiwan, Province of China",
                            Name_PT = "Formosa (Taiwan)"
                        },
                        new
                        {
                            Id = 209,
                            Bacen = "7722",
                            Initials = "TJ",
                            Name = "Tajikistan",
                            Name_PT = "Tadjiquistao, Republica do"
                        },
                        new
                        {
                            Id = 210,
                            Bacen = "7803",
                            Initials = "TZ",
                            Name = "Tanzania, United Republic of",
                            Name_PT = "Tanzânia, Republica Unida da"
                        },
                        new
                        {
                            Id = 211,
                            Bacen = "7765",
                            Initials = "TH",
                            Name = "Thailand",
                            Name_PT = "Tailândia"
                        },
                        new
                        {
                            Id = 212,
                            Bacen = "8001",
                            Initials = "TG",
                            Name = "Togo",
                            Name_PT = "Togo"
                        },
                        new
                        {
                            Id = 213,
                            Bacen = "8052",
                            Initials = "TK",
                            Name = "Tokelau",
                            Name_PT = "Toquelau, Ilhas"
                        },
                        new
                        {
                            Id = 214,
                            Bacen = "8109",
                            Initials = "TO",
                            Name = "Tonga",
                            Name_PT = "Tonga"
                        },
                        new
                        {
                            Id = 215,
                            Bacen = "8150",
                            Initials = "TT",
                            Name = "Trinidad and Tobago",
                            Name_PT = "Trinidad e Tobago"
                        },
                        new
                        {
                            Id = 216,
                            Bacen = "8206",
                            Initials = "TN",
                            Name = "Tunisia",
                            Name_PT = "Tunísia"
                        },
                        new
                        {
                            Id = 217,
                            Bacen = "8273",
                            Initials = "TR",
                            Name = "Turkey",
                            Name_PT = "Turquia"
                        },
                        new
                        {
                            Id = 218,
                            Bacen = "8249",
                            Initials = "TM",
                            Name = "Turkmenistan",
                            Name_PT = "Turcomenistão, Republica do"
                        },
                        new
                        {
                            Id = 219,
                            Bacen = "8230",
                            Initials = "TC",
                            Name = "Turks and Caicos Islands",
                            Name_PT = "Turcas e Caicos, Ilhas"
                        },
                        new
                        {
                            Id = 220,
                            Bacen = "8281",
                            Initials = "TV",
                            Name = "Tuvalu",
                            Name_PT = "Tuvalu"
                        },
                        new
                        {
                            Id = 221,
                            Bacen = "8338",
                            Initials = "UG",
                            Name = "Uganda",
                            Name_PT = "Uganda"
                        },
                        new
                        {
                            Id = 222,
                            Bacen = "8311",
                            Initials = "UA",
                            Name = "Ukraine",
                            Name_PT = "Ucrânia"
                        },
                        new
                        {
                            Id = 223,
                            Bacen = "2445",
                            Initials = "AE",
                            Name = "United Arab Emirates",
                            Name_PT = "Emirados Árabes Unidos"
                        },
                        new
                        {
                            Id = 224,
                            Bacen = "6289",
                            Initials = "GB",
                            Name = "United Kingdom",
                            Name_PT = "Reino Unido"
                        },
                        new
                        {
                            Id = 225,
                            Bacen = "2496",
                            Initials = "US",
                            Name = "United States",
                            Name_PT = "Estados Unidos"
                        },
                        new
                        {
                            Id = 226,
                            Bacen = "18664",
                            Initials = "UM",
                            Name = "United States Minor Outlying Islands",
                            Name_PT = "Ilhas Menores Distantes dos Estados Unidos"
                        },
                        new
                        {
                            Id = 227,
                            Bacen = "8451",
                            Initials = "UY",
                            Name = "Uruguay",
                            Name_PT = "Uruguai"
                        },
                        new
                        {
                            Id = 228,
                            Bacen = "8478",
                            Initials = "UZ",
                            Name = "Uzbekistan",
                            Name_PT = "Uzbequistão, Republica do"
                        },
                        new
                        {
                            Id = 229,
                            Bacen = "5517",
                            Initials = "VU",
                            Name = "Vanuatu",
                            Name_PT = "Vanuatu"
                        },
                        new
                        {
                            Id = 230,
                            Bacen = "8508",
                            Initials = "VE",
                            Name = "Venezuela",
                            Name_PT = "Venezuela"
                        },
                        new
                        {
                            Id = 231,
                            Bacen = "8583",
                            Initials = "VN",
                            Name = "Viet Nam",
                            Name_PT = "Vietnã"
                        },
                        new
                        {
                            Id = 232,
                            Bacen = "8630",
                            Initials = "VG",
                            Name = "Virgin Islands (British)",
                            Name_PT = "Virgens, Ilhas (Britânicas)"
                        },
                        new
                        {
                            Id = 233,
                            Bacen = "8664",
                            Initials = "VI",
                            Name = "Virgin Islands (U.S.)",
                            Name_PT = "Virgens, Ilhas (E.U.A.)"
                        },
                        new
                        {
                            Id = 234,
                            Bacen = "8753",
                            Initials = "WF",
                            Name = "Wallis and Futuna Islands",
                            Name_PT = "Wallis e Futuna, Ilhas"
                        },
                        new
                        {
                            Id = 235,
                            Bacen = "6858",
                            Initials = "EH",
                            Name = "Western Sahara",
                            Name_PT = "Saara Ocidental"
                        },
                        new
                        {
                            Id = 236,
                            Bacen = "3573",
                            Initials = "YE",
                            Name = "Yemen",
                            Name_PT = "Iémen"
                        },
                        new
                        {
                            Id = 237,
                            Bacen = "3883",
                            Initials = "YU",
                            Name = "Yugoslavia",
                            Name_PT = "Iugoslávia, República Fed. da"
                        },
                        new
                        {
                            Id = 238,
                            Bacen = "8907",
                            Initials = "ZM",
                            Name = "Zambia",
                            Name_PT = "Zâmbia"
                        },
                        new
                        {
                            Id = 239,
                            Bacen = "6653",
                            Initials = "ZW",
                            Name = "Zimbabwe",
                            Name_PT = "Zimbabue"
                        },
                        new
                        {
                            Id = 240,
                            Bacen = "1504",
                            Initials = "GG",
                            Name = "Bailiwick of Guernsey",
                            Name_PT = "Guernsey, Ilha do Canal (Inclui Alderney e Sark)"
                        },
                        new
                        {
                            Id = 241,
                            Bacen = "1508",
                            Initials = "JE",
                            Name = "Bailiwick of Jersey",
                            Name_PT = "Jersey, Ilha do Canal"
                        },
                        new
                        {
                            Id = 243,
                            Bacen = "3595",
                            Initials = "IM",
                            Name = "Isle of Man",
                            Name_PT = "Man, Ilha de"
                        },
                        new
                        {
                            Id = 246,
                            Bacen = "4985",
                            Initials = "ME",
                            Name = "Crna Gora (Montenegro)",
                            Name_PT = "Montenegro"
                        },
                        new
                        {
                            Id = 247,
                            Bacen = "7370",
                            Initials = "RS",
                            Name = "SÉRVIA",
                            Name_PT = "Republika Srbija"
                        },
                        new
                        {
                            Id = 248,
                            Bacen = "7600",
                            Initials = "SS",
                            Name = "Republic of South Sudan",
                            Name_PT = "Sudao do Sul"
                        },
                        new
                        {
                            Id = 249,
                            Bacen = "8958",
                            Name = "Zona del Canal de Panamá",
                            Name_PT = "Zona do Canal do Panamá"
                        },
                        new
                        {
                            Id = 252,
                            Bacen = "5780",
                            Initials = "PS",
                            Name = "Dawlat Filasṭīn",
                            Name_PT = "Palestina"
                        },
                        new
                        {
                            Id = 253,
                            Bacen = "153",
                            Initials = "AX",
                            Name = "Åland Islands",
                            Name_PT = "Aland, Ilhas"
                        },
                        new
                        {
                            Id = 255,
                            Bacen = "200",
                            Initials = "CW",
                            Name = "Curaçao",
                            Name_PT = "Curaçao"
                        },
                        new
                        {
                            Id = 256,
                            Bacen = "6998",
                            Initials = "SM",
                            Name = "Saint Martin",
                            Name_PT = "São Martinho, Ilha de (Parte Holandesa)"
                        },
                        new
                        {
                            Id = 258,
                            Bacen = "990",
                            Initials = "AN",
                            Name = "Bonaire",
                            Name_PT = "Bonaire"
                        },
                        new
                        {
                            Id = 259,
                            Bacen = "420",
                            Initials = "AQ",
                            Name = "Antartica",
                            Name_PT = "Antartica"
                        },
                        new
                        {
                            Id = 260,
                            Bacen = "3433",
                            Initials = "AU",
                            Name = "Heard Island and McDonald Islands",
                            Name_PT = "Ilha Herad e Ilhas Macdonald"
                        },
                        new
                        {
                            Id = 261,
                            Bacen = "6939",
                            Initials = "FR",
                            Name = "Saint-Barthélemy",
                            Name_PT = "São Bartolomeu"
                        },
                        new
                        {
                            Id = 262,
                            Bacen = "6980",
                            Initials = "SM",
                            Name = "Saint Martin",
                            Name_PT = "São Martinho, Ilha de (Parte Francesa)"
                        },
                        new
                        {
                            Id = 263,
                            Bacen = "7811",
                            Initials = "TF",
                            Name = "Terres Australes et Antarctiques Françaises",
                            Name_PT = "Terras Austrais e Antárcticas Francesas"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Location.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("IBGECode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("IdCountry")
                        .HasColumnType("int");

                    b.Property<string>("Initials")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NumberCode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("State");
                });

            modelBuilder.Entity("Domain.Entities.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("Displayable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BirthDate")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Identity")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Password")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Telephone")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Domain.Entities.Contact", b =>
                {
                    b.HasOne("Domain.Entities.Profile", null)
                        .WithMany("Contacts")
                        .HasForeignKey("ProfileId");
                });

            modelBuilder.Entity("Domain.Entities.Location.Address", b =>
                {
                    b.HasOne("Domain.Entities.Location.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.HasOne("Domain.Entities.Location.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("Domain.Entities.Location.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId");
                });

            modelBuilder.Entity("Domain.Entities.Location.City", b =>
                {
                    b.HasOne("Domain.Entities.Location.State", null)
                        .WithMany("Cities")
                        .HasForeignKey("StateId");
                });

            modelBuilder.Entity("Domain.Entities.Location.State", b =>
                {
                    b.HasOne("Domain.Entities.Location.Country", null)
                        .WithMany("States")
                        .HasForeignKey("CountryId");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId");
                });
#pragma warning restore 612, 618
        }
    }
}
